# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
  config.vm.provider "virtualbox" do |vb|
    vb.memory = "512"
  end
  
  config.vm.define "ubuntu-trusty64" do |d|
    d.vm.box = "ubuntu/trusty64"
    d.vm.provision "shell", inline: "apt-get update"
    d.vm.provision "docker", version: "1.9.0"
    d.vm.provision "shell", path: "../common/set_vim.sh"
    d.vm.provision "shell", path: "../common/install_dockercompose.sh"
  end
  
  config.vm.define "ubuntu-vivid64" do |d|
    d.vm.box = "ubuntu/vivid64"
    d.vm.provision "shell", inline: "apt-get update"
    d.vm.provision "docker", version: "1.9.0"
    d.vm.provision "shell", path: "../common/set_vim.sh"
    d.vm.provision "shell", path: "../common/install_dockercompose.sh"
  end
  
  config.vm.define "debian-jessie64" do |d|
    d.vm.box = "debian/jessie64"
    d.vm.provision "shell", inline: "apt-get install -y apt-transport-https && apt-get update"
    d.vm.provision "docker", version: "1.9.0"
    d.vm.provision "shell", path: "../common/set_vim.sh"
    d.vm.provision "shell", path: "../common/install_dockercompose.sh"
  end
  
  config.vm.define "debian-wheezy64" do |d|
    d.vm.box = "debian/wheezy64"
    d.vm.provision "shell", inline: "apt-get install -y apt-transport-https && apt-get update"
    d.vm.provision "docker", version: "1.9.0"
    d.vm.provision "shell", path: "../common/set_vim.sh"
    d.vm.provision "shell", path: "../common/install_dockercompose.sh"
  end
  
  config.vm.define "centos-7" do |d|
    d.vm.box = "puppetlabs/centos-7.0-64-puppet"
    d.vm.provision "shell", inline: "yum update -y && yum install -y epel-release"
    d.vm.provision "shell", inline: "(curl -sSL https://get.docker.com/ | sh) && service docker start && chkconfig docker on"
    d.vm.provision "shell", path: "../common/set_vim.sh"
    d.vm.provision "shell", path: "../common/install_dockercompose.sh"
  end
  
  config.vm.define "centos-6" do |d|
    d.vm.box = "puppetlabs/centos-6.6-64-puppet"
    d.vm.provision "shell", inline: "yum update -y && rpm -ivh http://dl.fedoraproject.org/pub/epel/6/x86_64/epel-release-6-8.noarch.rpm"
    d.vm.provision "docker"
    d.vm.provision "shell", path: "../common/set_vim.sh"
    d.vm.provision "shell", path: "../common/install_python2.7.10.sh"
    d.vm.provision "shell", path: "../common/install_dockercompose.sh"
  end
end
